### ISSUE TITLE
Locale-related failure when printing `µ` in `µs`

### ISSUE THREAD

**Issue by Gabriel439** [bos/criterion#205]
The motivation for this is the following issue reported against `bench`:

https://github.com/Gabriel439/bench/issues/40

The error is:

```
477495791d20:/app# bench true
benchmarking true
time                 453.2 bench: <stdout>: commitBuffer: invalid argument (invalid character)
```

This is due to `criterion` attempting to print `µs` and failing since the `µ` character in that string is encoded as UTF8 and fails on non-UTF8 locales.

This issue is similar to https://github.com/bos/criterion/issues/55 but I believe the fix applied for that issue was insufficiently general.  It only falls back to rendering `us` when the host operating system is windows, but it should probably use the current locale to detect whether or not to use the fallback.

I can work around this downstream in `bench` by using something like `setLocaleEncoding utf8` but I wanted to see if this could be fixed upstream instead.  If not, I can work around it on my end.

**Comment by RyanGlScott** [comment]
Yes, good point. I agree that this should be fixed upstream, but I think we should go even further upstream that `criterion` to fix this. That is to say, this is really an issue with the [`code-page`](https://github.com/RyanGlScott/code-page) library.

`criterion` uses the `withCP65001` function from `code-page` to ensure that we're always running in the `utf8` locale. As you've observed, however, this function only ever does anything on Windows—on other operating systems, it [does nothing](https://github.com/RyanGlScott/code-page/blob/acaaf427a89c116bf261a6c634504bfd186cca40/src/System/IO/CodePage.hs#L152). I naïvely assumed that Windows was the only operating system that needed any secret sauce to ensure that `µ` would be printed correctly, but you've proven me wrong.

I don't think it would be terribly difficult to change `code-page` to do the right thing here, luckily. You'd simply need to make the code in [`withCodePageVerbosity`](https://github.com/RyanGlScott/code-page/blob/acaaf427a89c116bf261a6c634504bfd186cca40/src/System/IO/CodePage.hs#L94-L153) run on all operating systems, and find a way to interpret the Windows–specific functions in a sensible way on other OSes. For examples, the `codePageEncoding` function could sensibly be defined on non–Windows OSes as:

```haskell
codePageEncoding :: CodePage -> TextEncoding
codePageEncoding cp
  | cp == cp65001
  = utf8
  | cp == cp1200
  = utf16le
  ...
  | otherwise
  = error $ "Don't know encoding for " ++ show cp
```

Want to give it a shot?

**Comment by RyanGlScott** [comment]
Hm... there is one complication with this plan, though. I forgot that `code-page` also exports this function:

```haskell
withCodePage :: CodePage -> IO a -> IO a 
```

Which allows you to specify an arbitrary code page. The problem is that I think there are Windows code pages that don't cleanly map to `TextEncoding`s on other operating systems (as indicated by the `error` case in my mockup of `codePageEncoding` in https://github.com/bos/criterion/issues/205#issuecomment-433619079).

Currently, other OSes won't notice if you call, say, `withCodePage 8675309` on them, since `withCodePage` is a no-op on non-Windows OSes. But if we re-implement `codePageEncoding` as suggested in https://github.com/bos/criterion/issues/205#issuecomment-433619079, then `withCodePage 8675309` will error out on non-Windows OSes.

I'm not sure if this is desirable or not. In practice, I think almost everyone just uses `withCP65001`, which cleanly maps to `utf8` and avoids this issue. On the other hand, it's a bit weird to have something which could work on Windows but error out on OSes other than Windows.

What do you think?

**Comment by RyanGlScott** [comment]
> In practice, I think almost everyone just uses `withCP65001`

I decided to verify that claim, and it appears to be correct. Searching for uses of `withCodePage` in Haskell projects on GitHub yields exactly one hit... which is in the `code-page` library itself. This makes me much less worried about introducing a breaking change to `withCodePage`, since I think no one will actually be affected by this breakage in practice.

To make things a little more palatable, I suppose I can change `withCodePageVerbosity` to accept another argument which controls how this function should work on non-Windows OSes. (For instance, if you wanted to recover the ability to have it not do anything at all on non-Windows OSes, this could be specified via some `Options` data type.) This would be another breaking change, but it turns out that no one is currently using `withCodePageVerbosity` either, so who cares :)

I went ahead and implemented this at the following `code-page` branch: https://github.com/RyanGlScott/code-page/tree/criterion-205 From my limited testing, this appears to do the right thing. Can you verify that `bench` works as you'd expect it to when built against this version of `code-page`?

**Comment by Gabriel439** [comment]
@RyanGlScott: It appears to still not work.  Here is the code I used to test it:

```nix
# test.nix

let
  overlay = pkgsNew: pkgsOld: {
    haskellPackages = pkgsOld.haskellPackages.override {
      overrides = haskellPackagesNew: haskellPackagesOld: {
        code-page = haskellPackagesNew.callPackage ./code-page.nix { };
      };
    };

    myImage = pkgsNew.dockerTools.buildImage {
      name = "bench-test";

      contents = [ pkgsNew.bench pkgsNew.bash ];

      runAsRoot = ''
        mkdir /tmp
      '';

      config = {
         Cmd = [ "/bin/bench" "true" ];
      };
    };
  };

  overlays = [ overlay ];

  nixpkgs = builtins.fetchTarball {
    url    = "https://github.com/NixOS/nixpkgs/archive/becbe4dbe16c367a486464f208a557d62d024eb9.tar.gz";
    sha256 = "1qiihxa2qdrij735rglfrx24nhn72kby44lkm1dxph395qy8fg1h";
  };

  pkgs = import nixpkgs { inherit overlays; };

in
  pkgs.myImage
```

```bash
$ docker load --input $(nix-build test.nix)
Loaded image: bench-test:latest

$ docker run bench-test:latest
benchmarking true
time                 1.081 ms   (1.078 ms .. 1.085 ms)
bench: <stdout>: commitBuffer: invalid argument (invalid character)
                     1.000 R

```

Do I need to change the `bench` package itself to use the function?

**Comment by RyanGlScott** [comment]
> Do I need to change the `bench` package itself to use the function?

You shouldn't, since `bench` is just invoking `criterion` (as `criterion` is the library that's wrapping all of its console output in `withCP65001` to set everything to UTF-8). Unfortunately, `docker load --input $(nix-build test.nix)` doesn't work on my machine, so I have no way of debugging the problem there.

It's possible that I fixed an entirely different problem than the one you're experiencing, though. Out of curiosity, what is the local workaround (that you alluded to in https://github.com/bos/criterion/issues/205#issue-374597402) that fixes the issue on `bench`'s side? On `code-page`'s side, I'm applying `hSetEncoding utf8` to each of `stdin`, `stdout`, and `stderr`, but perhaps that's not enough.

**Comment by Gabriel439** [comment]
@RyanGlScott: So in my experience the thing that works reliably is to not use `withCP65001` and to instead use `GHC.IO.setLocaleEncoding GHC.IO.utf8`.  That was the work-around I was planning to apply to `bench` if `criterion` couldn't be fixed

**Comment by RyanGlScott** [comment]
Huh. I could have sworn that I had tried `setLocaleEncoding` previously and it did nothing, but now that I try again, it actually does fix `bench`!

```
$ LANG=C ./bench true
benchmarking true
time                 252.2 μs   (248.0 μs .. 257.6 μs)
                     0.996 R²   (0.991 R² .. 0.999 R²)
mean                 255.7 μs   (252.2 μs .. 261.5 μs)
std dev              16.03 μs   (10.16 μs .. 23.37 μs)
variance introduced by outliers: 59% (severely inflated)
```

(That still doesn't fix the `cabal new-test` issues I mentioned in https://github.com/bos/criterion/issues/205#issuecomment-435596025, but that's never worked properly, so I'm not going to lose sleep over that.)

In any case, I've just pushed two new commits to the `criterion-205` branch of `code-page`. @Gabriel439, can you confirm that that fixes the issue on your end?

**Comment by Gabriel439** [comment]
@RyanGlScott: That doesn't fix it on my end.  I tried both using `docker` and with `LANG=C` and it still fails when built against revision fe573ebc1769150e77361bee17b91d6b01c46874 of `code-page`:

```
$ LANG=C result/bin/bench true          
benchmarking true
time                 1.502 ms   (1.500 ms .. 1.505 ms)
                     1.000 Rbench: <stdout>: commitBuffer: invalid argument (invalid character)
```


However, adding `GHC.IO.Encoding.setLocaleEncoding GHC.IO.Encoding.utf8` to `bench` did fix the problem:

```diff
diff --git a/src/Main.hs b/src/Main.hs
index d4ca20a..69e6a0a 100644
--- a/src/Main.hs
+++ b/src/Main.hs
@@ -14,6 +14,7 @@ import qualified Criterion.Main         as Criterion
 import qualified Criterion.Main.Options as Criterion
 import qualified Data.Text              as Text
 import qualified Data.Version
+import qualified GHC.IO.Encoding
 import qualified Options.Applicative
 import qualified Paths_bench
 import qualified System.IO              as IO
@@ -61,6 +62,8 @@ parser =
 
 main :: IO ()
 main = do
+    GHC.IO.Encoding.setLocaleEncoding GHC.IO.Encoding.utf8
+
     x <- Turtle.options "Command-line tool to benchmark other programs" parser
     case x of
         Options maybeBefore maybeAfter commands mode -> do
```

So if there's nothing else to do on your end I can still apply the fix on the side of `bench`

**Comment by RyanGlScott** [comment]
This is frustrating. I'm literally calling `GHC.IO.Encoding.setLocaleEncoding GHC.IO.Encoding.utf8` in `code-page`! I'm utterly baffled as to why that wouldn't work...

I'll try spinning up the NixOS Docker image to see if I can gain any insights from that.

**Comment by RyanGlScott** [comment]
@Gabriel439, just to make sure—you're also using the latest commit from `criterion`'s `master` branch (c0eb004823686f6545df13bbf733686eee68c838), correct?

**Comment by Gabriel439** [comment]
@RyanGlScott: No, I only pulled in the `code-page` changes.  Maybe that's why the fix didn't work on my end

**Comment by RyanGlScott** [comment]
> Maybe that's why the fix didn't work on my end

Indeed, the `master` branch of `criterion` contains a recent commit (mentioned in https://github.com/bos/criterion/issues/205#issuecomment-435596025) that actually makes `runMode` use `withCP65001` (previously, it was just limited to `defaultMain` and `defaultMainWith` for silly reasons).

What happens if you test `bench` with that?

**Comment by Gabriel439** [comment]
@RyanGlScott: Sorry for the delay.  I can confirm that when I also included the fix to `criterion` then it worked:

```
# docker run bench-test:6w2qan4c0r0hbxb5588ks5arbv5dw583
benchmarking true
time                 1.047 ms   (1.038 ms .. 1.055 ms)
                     0.999 R²   (0.999 R² .. 1.000 R²)
mean                 1.033 ms   (1.029 ms .. 1.039 ms)
std dev              16.45 μs   (12.96 μs .. 22.60 μs)
```

**Comment by RyanGlScott** [comment]
Hooray!

In that case, fixing this issue should just be a matter of making new releases of `code-page` and `criterion` with these fixes. I'll try to do so tonight.

**Comment by RyanGlScott** [comment]
I've just uploaded [`code-page-0.2`](http://hackage.haskell.org/package/code-page-0.2) and [`criterion-1.5.3.0`](http://hackage.haskell.org/package/criterion-1.5.3.0) to Hackage, so this should be fixed.

**Comment by Gabriel439** [comment]
@RyanGlScott: Thank you! 🙂
